[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
cowsay = "latest"
delta = "latest"
eza = "latest"
gh = "latest"
just = "latest"
llmfit = "latest"
node = "lts"
"npm:@anthropic-ai/claude-code" = { version = "latest", npm_args = "--ignore-scripts=false" }
opencode = "latest"
python = ["latest", "3.12"]
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }

[settings]
env_file = '.env'
idiomatic_version_file_enable_tools = ["python", "node"]
minimum_release_age = "0s"
